# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180126_2355'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='articlepost',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
        migrations.DeleteModel(
            name='ArticlePost',
        ),
    ]
