# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180127_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 9, 26, 16, 638334, tzinfo=utc)),
        ),
    ]
