# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180227_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 18, 22, 19, 165752, tzinfo=utc)),
        ),
    ]
