# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180227_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 18, 32, 6, 803865, tzinfo=utc)),
        ),
    ]
